# Generated by Django 2.2.6 on 2019-10-21 18:51

from django.db import migrations

def seed(apps, schema_editor):
    Food = apps.get_model('nutrition', 'Food')

    Food(name = 'Mozzarella Cheese', serving_size=1, serving_size_unit='oz', calories=85, fat=6.3, carbs=0.6, protien=6.3).save()
    Food(name = 'Cheddar Cheese', serving_size=1, serving_size_unit='oz', calories=115, fat=9.4, carbs=0.9, protien=6.5).save()
    Food(name = 'Swiss Cheese', serving_size=1, serving_size_unit='cup, shredded', calories=424, fat=33, carbs=1.6, protien=29).save()
    Food(name = 'Chicken', serving_size=3, serving_size_unit='oz', calories=187, fat=11, carbs=0, protien=20).save()
    Food(name = 'Ground Beef', serving_size=4, serving_size_unit='oz, cooked', calories=308, fat=20, carbs=0, protien=31).save()
    Food(name = 'Pork', serving_size=3, serving_size_unit='oz', calories=202, fat=12, carbs=0, protien=22).save()
    Food(name = 'Potatos', serving_size=1, serving_size_unit='potato', calories=161, fat=0.2, carbs=37, protien=4.3).save()
    Food(name = 'Tomatoes', serving_size=1, serving_size_unit='tomatoe', calories=22, fat=0.3, carbs=4.8, protien=1.1).save()
    Food(name = 'Onions', serving_size=1, serving_size_unit='onion', calories=41, fat=0.2, carbs=9.5, protien=1.3).save()
    Food(name = 'Oranges', serving_size=1, serving_size_unit='orange', calories=69, fat=0.2, carbs=18, protien=1.3).save()
    Food(name = 'Apples', serving_size=1, serving_size_unit='apple', calories=95, fat=0.3, carbs=25, protien=0.5).save()
    Food(name = 'Bananas', serving_size=1, serving_size_unit='banana', calories=105, fat=0.4, carbs=27, protien=1.3).save()
    Food(name = 'Grapes', serving_size=10, serving_size_unit='grapes', calories=34, fat=0.1, carbs=8.9, protien=0.4).save()
    Food(name = 'Wheat Bread', serving_size=1, serving_size_unit='slice', calories=77, fat=0.9, carbs=14, protien=3.1).save()
    Food(name = 'White Bread', serving_size=1, serving_size_unit='slice', calories=98, fat=1.2, carbs=18, protien=3.3).save()
    Food(name = 'Rice', serving_size=1, serving_size_unit='cup', calories=205, fat=0.4, carbs=45, protien=4.3).save()
    Food(name = 'Butter', serving_size=1, serving_size_unit='tbsp', calories=102, fat=12, carbs=0, protien=0.1).save()
    Food(name = 'Olive Oil', serving_size=1, serving_size_unit='tbsp', calories=119, fat=14, carbs=0, protien=0).save()
    Food(name = 'Eggs', serving_size=1, serving_size_unit='egg', calories=72, fat=4.8, carbs=0.4, protien=6.3).save()
    Food(name = 'Skim Milk', serving_size=1, serving_size_unit='cup', calories=83, fat=0.2, carbs=12, protien=8.3).save()
    Food(name = 'Sugar', serving_size=1, serving_size_unit='tsp', calories=16, fat=0, carbs=4.2, protien=0).save()

def fallow(apps, schema_editor):
    Food = apps.get_model('nutrition', 'Food')
    Food.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]